### PR TITLE
Food module fix

### PR DESCRIPTION
**Pull request by kenjiO**
I made a change on the back end where if a user attempts to create a foodItem that already exists it will update the quantity and category of the existing food item instead of creating another entry with the same name.

### CODE REVIEW

**Comment by jspaine** [comment]
Sounds a bit weird - if they click the new button they want to add a new item, if that's not possible there should just be a message saying why I think. Then they can use a more specific name if they really wanted to add it or just back out and edit the existing one if they didn't realize it was already there.

**Comment by kenjiO** [comment]
I thought is would be useful because I imagine that periodically the food bank will get a bunch of food items to add to the inventory.  Some item names are already there and some are not.  This way they can use the same form to add all of the items and don't have to bother searching to see if the item name already exists.

**Comment by jspaine** [comment]
You can type part of the name in the search box pretty quickly though, and what if the category isn't obvious and you choose the wrong one - you end up adding an item by mistake and maybe don't even realize.

The only way I can really see it working is if the Food Name field was an autocomplete/dropdown and showed matching foods and their categories. Clicking one would populate all the fields and change the Save button to an Update button

**Comment by kenjiO** [comment]
I added the autocomplete to the food name field so it suggests and uses and existing name if there is one.  It also sets the category to the same one as the existing food.  If the user decides to change the category, it will combine the old and existing food into the new category.  It doesn't populate the quantity because that is just meant to be the the quantity of new items being added.

**Comment by jspaine** [comment]
Sounds good!

**Comment by jspaine** [comment]
Good job, I only just got to trying it but this is pretty nice I think.

**Pull request merged**
